//! Shared emitter plumbing: rendering tokens to formatted source, and writing a generated
//! tree safely.
//!
//! The four emitters ([`models`], [`client`], [`meta`], [`fields`]) each take `&Ir` and return
//! [`GeneratedFile`]s. They share nothing else — no cross-emitter calls, no mutable state — so
//! each is independently testable and the output order is a pure function of the IR.
//!
//! Three rules are enforced here rather than trusted to each emitter:
//!
//! 1. **The generated tree is deleted and rewritten**, so a stale file from an operation that
//!    disappeared upstream cannot linger and keep compiling.
//! 2. **Writes are skipped when the bytes are unchanged**, which preserves mtimes so a no-op
//!    regenerate does not invalidate cargo's incremental cache.
//! 3. **No generated file exceeds [`MAX_LINES`]**, because the point of committing generated
//!    code is that a human can review its diff.

pub mod client;
pub mod fields;
pub mod meta;
pub mod models;

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use proc_macro2::TokenStream;

use crate::Result;
use crate::ir::Ir;

/// A generated file exceeding this is a bucketing failure, not something to shrug at: the
/// whole reason we commit generated code is that its diff is reviewable, and nobody reviews a
/// 9,000-line file. Busting the cap fails codegen and names the bucket rule to add.
pub const MAX_LINES: usize = 1500;

/// Directories owned entirely by codegen. Wiped and rewritten on every run.
///
/// Nothing hand-written may live under these paths — see CONTRIBUTING.md.
pub const GENERATED_ROOTS: &[&str] =
    &["crates/gitea-model/src/generated", "crates/gitea-client/src/generated"];

/// One file to be written, with a workspace-relative path.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    pub path: PathBuf,
    pub contents: String,
}

impl GeneratedFile {
    pub fn new(path: impl Into<PathBuf>, contents: impl Into<String>) -> Self {
        Self { path: path.into(), contents: contents.into() }
    }

    pub fn line_count(&self) -> usize {
        self.contents.lines().count()
    }
}

/// The banner every generated file opens with.
///
/// It records the **spec** hash and nothing else. No timestamp, no hostname, no generator
/// version, no absolute path — anything that varies between machines or runs would make every
/// regenerate produce a diff, and the diff is supposed to *be* the API changelog.
pub fn banner(spec_version: &str, spec_sha256: &str) -> String {
    format!(
        "// @generated by `cargo xtask codegen` from spec/gitea-{spec_version}.json\n\
         // (sha256:{short}). DO NOT EDIT — your changes will be deleted on the next run.\n\
         //\n\
         // To change this file, change the generator in crates/xtask/src/emit/ or the spec\n\
         // in spec/, then run `cargo xtask codegen`. See CONTRIBUTING.md.\n\n",
        short = &spec_sha256[..spec_sha256.len().min(16)],
    )
}

/// Render a module's tokens into formatted Rust source, prefixed with the banner.
///
/// `prettyplease` rather than shelling out to `rustfmt`, for two reasons that both bite in a
/// generated tree: its output does not depend on which `rustfmt` version a contributor has
/// installed, and — unlike `rustfmt`, which silently gives up on a line over `max_width` and
/// leaves it unformatted — it always breaks. A generator that occasionally emits 400-column
/// lines defeats the purpose of committing the output.
pub fn render(tokens: TokenStream, spec_version: &str, spec_sha256: &str) -> Result<String> {
    // The only place `syn` parsing happens. A malformed token stream fails here, during
    // generation, with the offending source in hand — rather than as a confusing `cargo build`
    // error 42k lines away.
    let file: syn::File = syn::parse2(tokens.clone()).map_err(|e| {
        format!(
            "generated tokens are not a valid Rust file: {e}\n\
             --- first 2000 chars of the offending stream ---\n{}",
            tokens.to_string().chars().take(2000).collect::<String>()
        )
    })?;

    Ok(format!("{}{}", banner(spec_version, spec_sha256), prettyplease::unparse(&file)))
}

/// What [`write_all`] should do with the rendered files.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Mode {
    /// Write the tree.
    Write,
    /// Write nothing; report which files would change. This is what CI runs, and it must not
    /// touch the working tree — otherwise a failing CI check would also dirty the checkout.
    Check,
}

#[derive(Debug, Default)]
pub struct Report {
    pub written: usize,
    pub unchanged: usize,
    /// Workspace-relative paths whose contents differ from what is on disk.
    pub changed: Vec<PathBuf>,
    /// Paths on disk under a generated root that the emitters did not produce.
    pub removed: Vec<PathBuf>,
    pub total_lines: usize,
}

impl Report {
    pub fn is_clean(&self) -> bool {
        self.changed.is_empty() && self.removed.is_empty()
    }

    pub fn render(&self) -> String {
        let mut s = format!(
            "{} files, {} lines: {} written, {} unchanged",
            self.written + self.unchanged,
            self.total_lines,
            self.written,
            self.unchanged,
        );
        if !self.removed.is_empty() {
            s.push_str(&format!(", {} removed", self.removed.len()));
        }
        s.push('\n');
        s
    }
}

/// Run all four emitters and return their files, sorted by path for deterministic output.
pub fn emit_all(ir: &Ir) -> Result<Vec<GeneratedFile>> {
    let mut files = Vec::new();
    files.extend(models::emit(ir)?);
    files.extend(meta::emit(ir)?);
    files.extend(fields::emit(ir)?);
    files.extend(client::emit(ir)?);

    files.sort_by(|a, b| a.path.cmp(&b.path));

    // Duplicate paths mean two emitters disagree about who owns a file. Silently letting the
    // last one win would make the output depend on emitter order.
    if let Some(dup) = first_duplicate(&files) {
        bail!("two emitters produced the same path: {}", dup.display());
    }

    let over: Vec<String> = files
        .iter()
        .filter(|f| f.line_count() > MAX_LINES)
        .map(|f| format!("  {} ({} lines)", f.path.display(), f.line_count()))
        .collect();
    if !over.is_empty() {
        bail!(
            "these generated files exceed the {MAX_LINES}-line review cap:\n{}\n\
             Add a bucket rule for the offending group to crates/xtask/src/overrides.toml \
             so the emitter splits them further.",
            over.join("\n")
        );
    }

    Ok(files)
}

fn first_duplicate(sorted: &[GeneratedFile]) -> Option<&Path> {
    sorted.windows(2).find(|w| w[0].path == w[1].path).map(|w| w[0].path.as_path())
}

/// Bring rendered files to their final, canonical form by running `rustfmt` over them.
///
/// # Why both `prettyplease` and `rustfmt`
///
/// `prettyplease` is what makes emission *correct*: it always breaks long lines, whereas
/// `rustfmt` silently gives up on a line over `max_width` and leaves it as-is — which in a
/// generated tree means occasional 400-column lines that defeat the point of committing the
/// output.
///
/// But `prettyplease` has no configuration, and this repository's `rustfmt.toml` sets
/// `use_small_heuristics = "Max"`, which collapses the wide `FieldSpec { … }` initializers onto
/// single lines. That left two formatters disagreeing about ~400 files, so
/// `cargo xtask codegen --check` and `cargo fmt --all --check` could not both pass: whichever
/// ran last won, and the other then failed. Worse, `rustfmt` follows `mod` declarations and
/// formats a file's whole module tree, so simply not naming the generated files does not
/// exclude them.
///
/// So the generator finishes the job itself: `prettyplease` for structure, then `rustfmt` for
/// the project's canonical style. Now `cargo fmt --all` is a no-op on generated code and the
/// two gates agree.
///
/// The cost is that output depends on the `rustfmt` version — which is exactly why
/// `rust-toolchain.toml` pins the toolchain. A contributor on a different toolchain would see
/// `codegen --check` fail, and the pinned channel is what prevents that.
fn rustfmt_in_place(dir: &Path, files: &[GeneratedFile], config: &Path) -> Result<()> {
    let paths: Vec<PathBuf> = files.iter().map(|f| dir.join(&f.path)).collect();
    if paths.is_empty() {
        return Ok(());
    }

    // One invocation over every file: 361 separate spawns would add ~10s to each codegen run.
    // `--config-path` explicitly: the staging directory is outside the repository, so
    // rustfmt's usual walk-upward search would not find `rustfmt.toml` and it would silently
    // format with defaults. The output must match what `cargo fmt` produces in-tree.
    let out = std::process::Command::new("rustfmt")
        .arg("--edition")
        .arg("2024")
        .arg("--config-path")
        .arg(config)
        .args(&paths)
        .output()
        .map_err(|e| {
            format!("could not run rustfmt (needed to canonicalize generated code): {e}")
        })?;

    if !out.status.success() {
        bail!(
            "rustfmt failed on the generated tree: {}\n\
             This usually means the emitters produced syntactically valid but unformattable \
             code. The generated files are in {}.",
            String::from_utf8_lossy(&out.stderr).trim(),
            dir.display()
        );
    }
    Ok(())
}

/// Write (or check) the generated tree.
///
/// Both modes render into a temporary directory and format it there, then compare against the
/// real tree. `Check` stops at the comparison — it must never touch the working tree, or a
/// failing CI check would also dirty the checkout it was reporting on.
pub fn write_all(root: &Path, files: &[GeneratedFile], mode: Mode) -> Result<Report> {
    let mut report = Report {
        total_lines: files.iter().map(GeneratedFile::line_count).sum(),
        ..Default::default()
    };

    // Staged in a temp dir so that formatting happens before anything is compared, and so a
    // `Check` run leaves no trace.
    //
    // The counter is not decoration. The name used to be the process id alone, which made the
    // staging directory shared by every concurrent `write_all` in one process — and since each
    // call opens by deleting it, two of them racing delete each other's staged files and fail
    // with a bare `NotFound` from somewhere in the middle of codegen. `cargo test` runs this
    // module's tests on several threads, so it showed up as a flake that came and went with
    // how many tests happened to be in the binary. Nothing here leaks into the output: only the
    // formatted *contents* are read back.
    static STAGE: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
    let stage = STAGE.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    let staging = std::env::temp_dir().join(format!("gea-codegen-{}-{stage}", std::process::id()));
    let _ = std::fs::remove_dir_all(&staging);
    for f in files {
        let abs = staging.join(&f.path);
        if let Some(parent) = abs.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&abs, &f.contents)?;
    }
    rustfmt_in_place(&staging, files, &root.join("rustfmt.toml"))?;

    // Re-read the formatted bytes; these are what gets compared and written.
    let mut formatted: Vec<GeneratedFile> = Vec::with_capacity(files.len());
    for f in files {
        let contents = std::fs::read_to_string(staging.join(&f.path))?;
        formatted.push(GeneratedFile::new(f.path.clone(), contents));
    }
    let _ = std::fs::remove_dir_all(&staging);

    report.total_lines = formatted.iter().map(GeneratedFile::line_count).sum();
    let files = &formatted[..];

    let wanted: BTreeMap<&Path, &GeneratedFile> =
        files.iter().map(|f| (f.path.as_path(), f)).collect();

    // Anything on disk under a generated root that we did not produce is stale — an operation
    // or model that disappeared upstream. It must go, or it keeps compiling and keeps being
    // referenced.
    for existing in existing_generated(root)? {
        if !wanted.contains_key(existing.as_path()) {
            report.removed.push(existing.clone());
            if mode == Mode::Write {
                std::fs::remove_file(root.join(&existing))?;
            }
        }
    }

    for f in files {
        let abs = root.join(&f.path);
        let same = std::fs::read_to_string(&abs).is_ok_and(|on_disk| on_disk == f.contents);
        if same {
            report.unchanged += 1;
            continue;
        }
        report.changed.push(f.path.clone());
        if mode == Mode::Write {
            if let Some(parent) = abs.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(&abs, &f.contents)?;
            report.written += 1;
        }
    }

    if mode == Mode::Write {
        prune_empty_dirs(root)?;
    }
    Ok(report)
}

/// Every `.rs` file currently under a generated root, workspace-relative.
fn existing_generated(root: &Path) -> Result<Vec<PathBuf>> {
    let mut out = Vec::new();
    for r in GENERATED_ROOTS {
        let dir = root.join(r);
        if dir.exists() {
            walk_rs(&dir, root, &mut out)?;
        }
    }
    out.sort();
    Ok(out)
}

fn walk_rs(dir: &Path, root: &Path, out: &mut Vec<PathBuf>) -> Result<()> {
    for entry in std::fs::read_dir(dir)? {
        let path = entry?.path();
        if path.is_dir() {
            walk_rs(&path, root, out)?;
        } else if path.extension().is_some_and(|e| e == "rs") {
            out.push(path.strip_prefix(root).unwrap_or(&path).to_path_buf());
        }
    }
    Ok(())
}

/// A group that loses all its operations leaves an empty directory behind, which is noise in
/// `git status` and confusing to read.
fn prune_empty_dirs(root: &Path) -> Result<()> {
    for r in GENERATED_ROOTS {
        prune(&root.join(r))?;
    }
    Ok(())
}

fn prune(dir: &Path) -> Result<bool> {
    if !dir.is_dir() {
        return Ok(false);
    }
    let mut empty = true;
    for entry in std::fs::read_dir(dir)? {
        let path = entry?.path();
        if path.is_dir() {
            if !prune(&path)? {
                empty = false;
            }
        } else {
            empty = false;
        }
    }
    if empty {
        std::fs::remove_dir(dir)?;
    }
    Ok(empty)
}

#[cfg(test)]
mod tests {
    use super::*;
    use quote::quote;

    /// A throwaway workspace root.
    ///
    /// It carries a copy of the real `rustfmt.toml` because `write_all` now post-formats with
    /// `--config-path`, so a root without one would exercise a path that never happens in
    /// practice — and would fail for a reason unrelated to what each test is checking.
    fn temp_root(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("gea-emit-{tag}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::copy(crate::workspace_root().join("rustfmt.toml"), dir.join("rustfmt.toml"))
            .unwrap();
        dir
    }

    #[test]
    fn render_prepends_the_banner_and_formats() {
        let out = render(quote! { pub struct A { pub b : i64 } }, "1.27.2", "abcdef1234567890ff")
            .unwrap();
        assert!(out.starts_with("// @generated"), "banner missing:\n{out}");
        assert!(out.contains("sha256:abcdef1234567890"));
        // prettyplease must have broken the struct across lines.
        assert!(out.contains("pub struct A {\n"), "not formatted:\n{out}");
    }

    #[test]
    fn banner_carries_nothing_that_varies_between_runs() {
        // A timestamp or hostname here would make every regenerate produce a diff, which
        // would destroy the property that the diff *is* the API changelog.
        let a = banner("1.27.2", "deadbeefdeadbeef");
        let b = banner("1.27.2", "deadbeefdeadbeef");
        assert_eq!(a, b);
    }

    #[test]
    fn malformed_tokens_fail_at_generation_time_with_context() {
        // Not a valid file: a bare expression. The error must carry the offending source,
        // because otherwise this surfaces as an inscrutable rustc error later.
        let err = render(quote! { 1 + 1 }, "1.27.2", "aa").unwrap_err().to_string();
        assert!(err.contains("not a valid Rust file"), "{err}");
        assert!(err.contains("offending stream"), "{err}");
    }

    #[test]
    fn check_mode_writes_nothing() {
        let tmp = temp_root("check");
        let files =
            vec![GeneratedFile::new("crates/gitea-model/src/generated/a.rs", "pub fn a() {}\n")];
        let report = write_all(&tmp, &files, Mode::Check).unwrap();

        assert!(!report.is_clean(), "a missing file should count as changed");
        assert_eq!(report.written, 0);
        assert!(!tmp.join("crates/gitea-model/src/generated/a.rs").exists());

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn unchanged_files_are_not_rewritten() {
        let tmp = temp_root("nochange");
        let files =
            vec![GeneratedFile::new("crates/gitea-model/src/generated/a.rs", "pub fn a() {}\n")];

        assert_eq!(write_all(&tmp, &files, Mode::Write).unwrap().written, 1);
        // Second run must skip the write, so mtimes survive and cargo's incremental cache
        // is not invalidated by a no-op regenerate.
        let second = write_all(&tmp, &files, Mode::Write).unwrap();
        assert_eq!(second.written, 0);
        assert_eq!(second.unchanged, 1);
        assert!(second.is_clean());

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn stale_files_are_removed() {
        let tmp = temp_root("stale");
        let gen_dir = tmp.join("crates/gitea-model/src/generated");
        std::fs::create_dir_all(&gen_dir).unwrap();
        // An operation that disappeared upstream. Left in place it would keep compiling.
        std::fs::write(gen_dir.join("gone.rs"), "pub fn gone() {}\n").unwrap();

        let files =
            vec![GeneratedFile::new("crates/gitea-model/src/generated/a.rs", "pub fn a() {}\n")];
        let report = write_all(&tmp, &files, Mode::Write).unwrap();

        assert_eq!(report.removed.len(), 1);
        assert!(!gen_dir.join("gone.rs").exists());

        let _ = std::fs::remove_dir_all(&tmp);
    }
}
