//! `cargo xtask update-spec --version v1.27.2`.
//!
//! Fetches the Gitea Swagger template at a git tag and turns it into a canonical JSON
//! document the generator can read.
//!
//! ## Why a Go template can be treated as JSON
//!
//! Upstream's spec is `templates/swagger/v1_json.tmpl` — a Go template, not a JSON file. It
//! happens to parse as valid JSON because its only two placeholders sit *inside* JSON string
//! values:
//!
//! ```text
//! "version":  "{{.SwaggerAppVer}}"
//! "basePath": "{{.SwaggerAppSubUrl}}/api/v1"
//! ```
//!
//! That "happens to" is load-bearing and fragile, so [`check_placeholders`] asserts there are
//! **exactly two** placeholders and that they are exactly those two. A third placeholder — or
//! one of these moving somewhere structural — means substitution is no longer sufficient and
//! the whole approach needs revisiting. Hard-erroring here is the entire reason we are allowed
//! to pretend this file is JSON.
//!
//! ## Why HTTP is `curl`
//!
//! `xtask` has no HTTP crate on purpose. Adding `reqwest` to the generator would put a TLS
//! stack and an async runtime on the critical path of `cargo xtask --help`, to fetch one file
//! once per Gitea release. Shelling out to `curl` is the right amount of machinery for a
//! developer-only tool.

use std::collections::BTreeMap;
use std::path::Path;
use std::process::Command;

use serde_json::Value;

use crate::Result;
use crate::spec::{self, Lock, sha256_hex};

/// The only two placeholders the substitution step knows how to handle.
pub const EXPECTED_PLACEHOLDERS: [&str; 2] = ["{{.SwaggerAppSubUrl}}", "{{.SwaggerAppVer}}"];

/// Every Gitea API is mounted here. Upstream writes `{{AppSubUrl}}/api/v1` because a
/// self-hosted instance may live under a path prefix; the *client* learns that prefix from the
/// configured host URL at runtime, so the vendored spec pins the bare API root.
pub const BASE_PATH: &str = "/api/v1";

pub fn run(root: &Path, version: &str, dry_run: bool, verify: bool) -> Result<()> {
    let (tag, bare) = normalize_version(version)?;
    let url = spec::source_url(&tag);

    eprintln!("fetching {url}");
    let upstream = fetch(&url)?;
    let upstream_sha = sha256_hex(upstream.as_bytes());
    eprintln!("  {} bytes, sha256 {}", upstream.len(), upstream_sha);

    check_placeholders(&upstream)?;

    let json = canonicalize(&upstream, &bare)?;
    let canonical_sha = sha256_hex(json.as_bytes());

    let lock = Lock {
        tag: tag.clone(),
        version: bare.clone(),
        source: url,
        upstream: "v1_json.tmpl".to_owned(),
        upstream_sha256: upstream_sha,
        canonical: spec::canonical_name(&bare),
        canonical_sha256: canonical_sha.clone(),
    };

    // Parse before writing anything. A spec we cannot load is not a spec we should commit.
    let parsed: crate::swagger::Spec = serde_json::from_str(&json)
        .map_err(|e| format!("canonical JSON does not match our Swagger model: {e}"))?;
    let stats = crate::stats::Stats::compute(&parsed);
    eprint!("{}", stats.render());

    if dry_run {
        eprintln!("dry run: nothing written");
        eprintln!("  would write {}", spec::tmpl_path(root).display());
        eprintln!("  would write {}", spec::spec_dir(root).join(&lock.canonical).display());
        eprintln!("  would write {}", spec::lock_path(root).display());
        eprintln!("  canonical sha256 {canonical_sha}");
        return Ok(());
    }

    let dir = spec::spec_dir(root);
    std::fs::create_dir_all(&dir)?;
    let mut wrote = 0;
    wrote += usize::from(write_if_changed(&spec::tmpl_path(root), upstream.as_bytes())?);
    wrote += usize::from(write_if_changed(&dir.join(&lock.canonical), json.as_bytes())?);

    let lock_text = format!(
        "# @generated by `cargo xtask update-spec`. DO NOT EDIT.\n\
         #\n\
         # `upstream_sha256` proves what we fetched; `canonical_sha256` proves what the\n\
         # generator read and is the value stamped into every generated file's header.\n\n{}",
        toml::to_string_pretty(&lock)?
    );
    wrote += usize::from(write_if_changed(&spec::lock_path(root), lock_text.as_bytes())?);
    for stale in remove_stale_canonicals(&dir, &lock.canonical)? {
        eprintln!("  removed:   {} (superseded by {})", stale.display(), lock.canonical);
    }

    if wrote == 0 {
        eprintln!("spec/ is already at {} — nothing to do", lock.tag);
    } else {
        eprintln!("wrote {wrote} file(s) under spec/ for {}", lock.tag);
        eprintln!("  next: cargo xtask codegen --check-names");
    }
    if !verify {
        // The expected counts in stats.rs are for ONE version, so on a bump `verify` fails
        // by design until a human re-derives them. The spec-drift workflow passes
        // --no-verify to get the files written and leaves that step in the PR checklist;
        // the counts it printed above are the input to it.
        eprintln!(
            "note: --no-verify given; update the expected counts in crates/xtask/src/stats.rs"
        );
        return Ok(());
    }
    stats.verify(&bare)
}

/// Deletes every `gitea-v*.json` under `dir` other than `keep`, returning what it removed.
///
/// `lock.toml` names exactly one canonical file, and [`crate::spec::load`] reads only that
/// one, so a previous version's file is dead weight — 850 KB of it — that a reader has to
/// notice is unreferenced. Removing it here keeps "the vendored spec" a single file.
fn remove_stale_canonicals(dir: &Path, keep: &str) -> Result<Vec<std::path::PathBuf>> {
    let mut removed = Vec::new();
    for entry in std::fs::read_dir(dir)? {
        let path = entry?.path();
        let name = path.file_name().and_then(|n| n.to_str()).unwrap_or_default();
        if name.starts_with("gitea-v") && name.ends_with(".json") && name != keep {
            std::fs::remove_file(&path)?;
            removed.push(path);
        }
    }
    removed.sort();
    Ok(removed)
}

/// Accepts `v1.27.2` or `1.27.2` and returns `(tag, bare)`.
fn normalize_version(v: &str) -> Result<(String, String)> {
    let v = v.trim();
    if v.is_empty() {
        bail!("--version is empty; expected something like v1.27.2");
    }
    let bare = v.strip_prefix('v').unwrap_or(v);
    if !bare.starts_with(|c: char| c.is_ascii_digit()) {
        bail!("--version {v:?} does not look like a Gitea release tag (expected e.g. v1.27.2)");
    }
    Ok((format!("v{bare}"), bare.to_owned()))
}

pub(crate) fn fetch(url: &str) -> Result<String> {
    let out = Command::new("curl")
        .args([
            "--silent",
            "--show-error",
            "--fail",
            "--location",
            "--proto",
            "=https",
            "--tlsv1.2",
            url,
        ])
        .output()
        .map_err(|e| {
            format!(
                "could not run curl: {e}\n  \
                 xtask deliberately has no HTTP client of its own; install curl or download \
                 {url} by hand into spec/v1_json.tmpl"
            )
        })?;

    if !out.status.success() {
        bail!(
            "curl failed ({}): {}\n  url: {url}",
            out.status,
            String::from_utf8_lossy(&out.stderr).trim(),
        );
    }
    Ok(String::from_utf8(out.stdout)?)
}

/// Every `{{ … }}` occurrence in the template, in order of appearance.
pub fn find_placeholders(s: &str) -> Vec<&str> {
    let mut out = Vec::new();
    let mut rest = s;
    while let Some(start) = rest.find("{{") {
        let after = &rest[start..];
        match after.find("}}") {
            Some(end) => {
                out.push(&after[..end + 2]);
                rest = &after[end + 2..];
            }
            // An unterminated `{{` is not something we should guess about.
            None => {
                out.push(after);
                break;
            }
        }
    }
    out
}

/// The guard that lets us treat a Go template as JSON. See the module docs.
pub fn check_placeholders(s: &str) -> Result<()> {
    let found = find_placeholders(s);
    let mut counts: BTreeMap<&str, usize> = BTreeMap::new();
    for p in &found {
        *counts.entry(*p).or_default() += 1;
    }

    let unexpected: Vec<&str> =
        counts.keys().copied().filter(|p| !EXPECTED_PLACEHOLDERS.contains(p)).collect();

    if !unexpected.is_empty() {
        bail!(
            "upstream template grew {} placeholder(s) we do not know how to substitute:\n  {}\n\
             \n  Known and handled:\n    {}\n\
             \n  This matters because the vendored spec is only valid JSON as long as every\n  \
             placeholder sits inside a JSON string value. A new one may not, and substituting\n  \
             blindly would produce a spec that is subtly wrong rather than obviously broken.\n  \
             Inspect the upstream diff, then teach update_spec.rs about it.",
            unexpected.len(),
            unexpected.join("\n  "),
            EXPECTED_PLACEHOLDERS.join("\n    "),
        );
    }

    if found.len() != EXPECTED_PLACEHOLDERS.len() {
        bail!(
            "expected exactly {} placeholders, found {}: {:?}\n  \
             A repeated placeholder means upstream now interpolates in a second position; \
             confirm the new position is inside a JSON string before proceeding.",
            EXPECTED_PLACEHOLDERS.len(),
            found.len(),
            found,
        );
    }

    Ok(())
}

/// Substitutes the placeholders, pins `info.version` and `basePath`, and re-serializes with
/// **recursively sorted keys** and two-space indent.
///
/// Sorting is the point. Upstream's key order is whatever Go's map iteration and struct field
/// order produced; if the generator read that order, a cosmetic upstream reshuffle would move
/// hundreds of generated functions and every review of a spec bump would be unreadable.
pub fn canonicalize(template: &str, version: &str) -> Result<String> {
    // Substituting `AppSubUrl` with the empty string already yields `/api/v1`; we overwrite
    // `basePath` explicitly below anyway, so the substitution only has to make the document
    // parse.
    let substituted =
        template.replace("{{.SwaggerAppVer}}", version).replace("{{.SwaggerAppSubUrl}}", "");

    let mut value: Value = serde_json::from_str(&substituted).map_err(|e| {
        format!(
            "the de-templated spec is not valid JSON: {e}\n  \
             This is the failure mode the placeholder guard exists to prevent — a placeholder \
             must have appeared outside a JSON string value."
        )
    })?;

    let obj = value.as_object_mut().ok_or("the spec's root is not a JSON object")?;
    obj.get_mut("info")
        .and_then(Value::as_object_mut)
        .ok_or("the spec has no `info` object")?
        .insert("version".to_owned(), Value::String(version.to_owned()));
    obj.insert("basePath".to_owned(), Value::String(BASE_PATH.to_owned()));

    let sorted = sort_keys(value);
    let mut out = serde_json::to_string_pretty(&sorted)?;
    out.push('\n');
    Ok(out)
}

/// Rebuilds every object with its keys in sorted order.
///
/// The workspace enables serde_json's `preserve_order`, so `serde_json::Map` is
/// insertion-ordered and *will* faithfully reproduce upstream's order unless we do this. The
/// sort therefore has to be explicit: collect into a `BTreeMap`, then re-insert.
fn sort_keys(v: Value) -> Value {
    match v {
        Value::Object(map) => {
            let sorted: BTreeMap<String, Value> = map.into_iter().collect();
            let mut out = serde_json::Map::with_capacity(sorted.len());
            for (k, v) in sorted {
                out.insert(k, sort_keys(v));
            }
            Value::Object(out)
        }
        // Arrays keep their order: in JSON an array's order is semantic, and reordering
        // `enum` or `required` would change meaning (and churn generated variant order).
        Value::Array(items) => Value::Array(items.into_iter().map(sort_keys).collect()),
        other => other,
    }
}

/// Write only when the bytes differ, so a no-op `update-spec` does not touch mtimes and
/// invalidate cargo's incremental cache for the whole workspace. Returns whether it wrote.
fn write_if_changed(path: &Path, bytes: &[u8]) -> Result<bool> {
    if std::fs::read(path).is_ok_and(|existing| existing == bytes) {
        eprintln!("  unchanged: {}", path.display());
        return Ok(false);
    }
    std::fs::write(path, bytes)?;
    eprintln!("  wrote:     {}", path.display());
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;

    const TWO: &str = r#"{"info":{"version":"{{.SwaggerAppVer}}"},
                          "basePath":"{{.SwaggerAppSubUrl}}/api/v1"}"#;

    #[test]
    fn accepts_exactly_the_two_known_placeholders() {
        check_placeholders(TWO).unwrap();
    }

    #[test]
    fn rejects_a_third_placeholder() {
        // The bug this prevents: upstream adds `{{AppName}}` (or moves a placeholder into a
        // structural position), we substitute only the two we know, and the resulting
        // "canonical" spec is either invalid JSON or — far worse — valid JSON containing a
        // literal `{{...}}` that silently becomes a doc comment or a default value.
        let three = TWO.replace("api/v1", "api/v1/{{AppName}}");
        let err = check_placeholders(&three).unwrap_err().to_string();
        assert!(err.contains("{{AppName}}"), "error should name the offender: {err}");
    }

    #[test]
    fn rejects_a_repeated_known_placeholder() {
        let dup = format!("{TWO} {{{{.SwaggerAppVer}}}}");
        assert!(check_placeholders(&dup).is_err());
    }

    #[test]
    fn canonicalize_sorts_keys_recursively() {
        // preserve_order is enabled workspace-wide, so without an explicit sort this test
        // would see upstream's order and generated code would move whenever upstream
        // reshuffled a struct.
        let out = canonicalize(
            r#"{"swagger":"2.0","info":{"version":"{{.SwaggerAppVer}}","title":"t"},
                "basePath":"{{.SwaggerAppSubUrl}}/api/v1",
                "definitions":{"Zed":{"type":"object"},"Alpha":{"type":"object"}}}"#,
            "1.27.2",
        )
        .unwrap();
        let alpha = out.find("\"Alpha\"").unwrap();
        let zed = out.find("\"Zed\"").unwrap();
        assert!(alpha < zed, "definitions must be key-sorted:\n{out}");
        assert!(out.find("\"basePath\"").unwrap() < out.find("\"definitions\"").unwrap());
    }

    #[test]
    fn canonicalize_pins_version_and_base_path() {
        let out = canonicalize(TWO, "1.27.2").unwrap();
        let v: Value = serde_json::from_str(&out).unwrap();
        assert_eq!(v["info"]["version"], "1.27.2");
        // Not `{{AppSubUrl}}/api/v1`, and not an instance's subpath either: the runtime owns
        // the prefix.
        assert_eq!(v["basePath"], "/api/v1");
    }

    #[test]
    fn canonicalize_indents_with_two_spaces_and_ends_with_a_newline() {
        let out = canonicalize(TWO, "1.27.2").unwrap();
        assert!(out.contains("\n  \""), "expected two-space indent:\n{out}");
        assert!(out.ends_with('\n'));
    }

    #[test]
    fn arrays_keep_their_order() {
        // Sorting an `enum` array would reorder generated open-enum variants for no reason,
        // and sorting `required` would be a meaningless diff.
        let out = canonicalize(
            r#"{"info":{"version":"{{.SwaggerAppVer}}"},
                "basePath":"{{.SwaggerAppSubUrl}}/api/v1",
                "x":{"enum":["zebra","apple"]}}"#,
            "1.0.0",
        )
        .unwrap();
        assert!(out.find("zebra").unwrap() < out.find("apple").unwrap());
    }

    #[test]
    fn stale_canonical_files_are_removed_but_the_current_one_and_the_rest_are_kept() {
        // A bump from v1.27.2 to v1.27.3 writes gitea-v1.27.3.json; without this, the
        // v1.27.2 file lingers next to it, unreferenced by lock.toml, and the next reader
        // has two "vendored specs" to choose between.
        let dir = tempfile::tempdir().unwrap();
        for name in ["gitea-v1.27.2.json", "gitea-v1.27.3.json", "v1_json.tmpl", "lock.toml"] {
            std::fs::write(dir.path().join(name), "x").unwrap();
        }
        let removed = remove_stale_canonicals(dir.path(), "gitea-v1.27.3.json").unwrap();
        assert_eq!(removed, vec![dir.path().join("gitea-v1.27.2.json")]);
        let mut left: Vec<String> = std::fs::read_dir(dir.path())
            .unwrap()
            .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
            .collect();
        left.sort();
        assert_eq!(left, ["gitea-v1.27.3.json", "lock.toml", "v1_json.tmpl"]);
    }

    #[test]
    fn version_accepts_bare_or_prefixed() {
        assert_eq!(normalize_version("v1.27.2").unwrap(), ("v1.27.2".into(), "1.27.2".into()));
        assert_eq!(normalize_version("1.27.2").unwrap(), ("v1.27.2".into(), "1.27.2".into()));
        assert!(normalize_version("main").is_err());
    }
}
